[package]
name = "my_library"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
datafusion-python = "38.0.1"

[dependencies.pyo3]
version = "0.20"
features = ["abi3-py38"]
